Allow the tool to run on linux
On Linux, using Python 2.7.15rc1, I get the following error message:

```
  File "UnicodeConverter.pyw", line 29, in <module>
    root.iconbitmap(default=datafile)                               ## Declare the small icon shown on window
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1699, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, '-default', default)
_tkinter.TclError: wrong # args: should be "wm iconbitmap window ?bitmap?"
```

I am not sure what the root cause is but just catching (and ignoring) exceptions on `root.iconbitmap(default=datafile)` allows the program to run